/* INSERT QUERY NO: 1 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'50419135', 'ADELIYAADHIMI RISKY NURROCHMAH'
);

/* INSERT QUERY NO: 2 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'50419339', 'AHMAD NAUFAL FADHIL'
);

/* INSERT QUERY NO: 3 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'50419515', 'ALIFA NUR RIZQILLAH'
);

/* INSERT QUERY NO: 4 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'50419666', 'AMMAR RIDWAN DARMA'
);

/* INSERT QUERY NO: 5 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'57419107', 'ANANDA AGUSTIANTO'
);

/* INSERT QUERY NO: 6 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'51419207', 'AXIS RAMADHAN'
);

/* INSERT QUERY NO: 7 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'51419933', 'DWI PERTIWI ANI'
);

/* INSERT QUERY NO: 8 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'52419086', 'EVITA PRAMESTI'
);

/* INSERT QUERY NO: 9 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'52419139', 'FADIYAH NAZIHFA UKHTI'
);

/* INSERT QUERY NO: 10 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'52419155', 'FAHD ERLANGGA BRAJA MUSTI'
);

/* INSERT QUERY NO: 11 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'52419433', 'FIELA JUNITA AZHARI'
);

/* INSERT QUERY NO: 12 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'52419564', 'GAMMARAL VENERDI DEWAJI'
);

/* INSERT QUERY NO: 13 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'52419567', 'GARDENA CITRA PUSPITA'
);

/* INSERT QUERY NO: 14 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'52419856', 'I GEDE BAYU DUARSANAYASA'
);

/* INSERT QUERY NO: 15 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'52419950', 'ILHAM YUNUS HAMDANI'
);

/* INSERT QUERY NO: 16 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'52419960', 'IMAM AGUS FAISAL'
);

/* INSERT QUERY NO: 17 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'53419331', 'KONSTAN DAMAI TELAUMBANUA'
);

/* INSERT QUERY NO: 18 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'53419382', 'LEEVINKIE HAUWTARI TANUMIHARJA'
);

/* INSERT QUERY NO: 19 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419032', 'MUHAMMAD ARIEF RUBBYANSYAH'
);

/* INSERT QUERY NO: 20 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419049', 'MUHAMMAD AULIA RASYID'
);

/* INSERT QUERY NO: 21 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419118', 'MUHAMMAD FADILLAH RASYID'
);

/* INSERT QUERY NO: 22 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419146', 'MUHAMMAD FARHAN'
);

/* INSERT QUERY NO: 23 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419164', 'MUHAMMAD FATA NURYANTO'
);

/* INSERT QUERY NO: 24 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419229', 'MUHAMMAD ILHAM HANIFAN'
);

/* INSERT QUERY NO: 25 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419406', 'MUHAMMAD RIFQI AL FURQON'
);

/* INSERT QUERY NO: 26 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419745', 'NAZWA SAPTA PRADANA'
);

/* INSERT QUERY NO: 27 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419786', 'NILA APRILLIA KARTIKA PUTRI'
);

/* INSERT QUERY NO: 28 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419997', 'PATRICIA MATTHEA JOVENA'
);

/* INSERT QUERY NO: 29 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'55419360', 'RAYHAN NAUFAL HERLANO'
);

/* INSERT QUERY NO: 30 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'55419813', 'SAFIRA SAFA FATHIMAYA'
);

/* INSERT QUERY NO: 31 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'55419968', 'SENNA ANNABA AHMAD'
);

/* INSERT QUERY NO: 32 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'56419004', 'SHAFIAH QONITA'
);

/* INSERT QUERY NO: 33 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'56419080', 'SINTARIO SATYA'
);

/* INSERT QUERY NO: 34 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'56419251', 'SYIFA HAMEZA HAMID'
);

/* INSERT QUERY NO: 35 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'56419513', 'VINSENSIUS HARYO BHASKORO HADI'
);

/* INSERT QUERY NO: 36 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'56419565', 'WALDO FELIX'
);

/* INSERT QUERY NO: 37 */
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'56419764', 'YULYANO THOMAS DJAYA'
);
