INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'50419135', 'ADELIYAADHIMI RISKY NURROCHMAH'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'50419339', 'AHMAD NAUFAL FADHIL'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'50419515', 'ALIFA NUR RIZQILLAH'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'50419666', 'AMMAR RIDWAN DARMA'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'57419107', 'ANANDA AGUSTIANTO'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'51419207', 'AXIS RAMADHAN'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'51419933', 'DWI PERTIWI ANI'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'52419086', 'EVITA PRAMESTI'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'52419139', 'FADIYAH NAZIHFA UKHTI'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'52419155', 'FAHD ERLANGGA BRAJA MUSTI'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'52419433', 'FIELA JUNITA AZHARI'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'52419564', 'GAMMARAL VENERDI DEWAJI'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'52419567', 'GARDENA CITRA PUSPITA'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'52419856', 'I GEDE BAYU DUARSANAYASA'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'52419950', 'ILHAM YUNUS HAMDANI'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'52419960', 'IMAM AGUS FAISAL'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'53419331', 'KONSTAN DAMAI TELAUMBANUA'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'53419382', 'LEEVINKIE HAUWTARI TANUMIHARJA'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419032', 'MUHAMMAD ARIEF RUBBYANSYAH'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419049', 'MUHAMMAD AULIA RASYID'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419118', 'MUHAMMAD FADILLAH RASYID'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419146', 'MUHAMMAD FARHAN'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419164', 'MUHAMMAD FATA NURYANTO'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419229', 'MUHAMMAD ILHAM HANIFAN'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419406', 'MUHAMMAD RIFQI AL FURQON'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419745', 'NAZWA SAPTA PRADANA'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419786', 'NILA APRILLIA KARTIKA PUTRI'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'54419997', 'PATRICIA MATTHEA JOVENA'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'55419360', 'RAYHAN NAUFAL HERLANO'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'55419813', 'SAFIRA SAFA FATHIMAYA'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'55419968', 'SENNA ANNABA AHMAD'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'56419004', 'SHAFIAH QONITA'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'56419080', 'SINTARIO SATYA'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'56419251', 'SYIFA HAMEZA HAMID'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'56419513', 'VINSENSIUS HARYO BHASKORO HADI'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'56419565', 'WALDO FELIX'
);
INSERT INTO mahasiswa(NPM, NAMA)
VALUES
(
'56419764', 'YULYANO THOMAS DJAYA'
);
